---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sys-uptime-exporter
  namespace: sys-argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: https://lukas-pastva.github.io/helm-chartie/
    targetRevision: 0.2.21
    chart: helm-chartie
    helm:
      values: |-
        pods:
          sys-uptime-exporter:
            repo: lukaspastva/uptime-exporter:latest
            simpleResources: 100
            ports:
              - name: http
                port: 9199
            serviceMonitorEnabled: true
            envs:
              - name: CONFIG_FILE
                value: |
                  config:
                    prometheus_url: "http://prometheus-operated.monitoring:9090"
                    metrics:
                      - name: test-metric
                        measureStart: "2023-08-28T18:53:46Z"
                        queries:
                          - queryType: "kube_deployment_status_replicas"
                            cluster: test-cluster
                            namespace: test-namespace
                            name: test-deployment
                          - queryType: "probe_success"
                            cluster: test-cluster
                            instance: "https://google.com"
                    uptimes:
                      - start: "2023-11-16T8:00:00Z"
                        end: "2023-11-28T8:00:00Z"

  destination:
    server: "https://kubernetes.default.svc"
    namespace: sys-uptime-exporter
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
