apiVersion: v1
kind: Pod
metadata:
  name: uptime-exporter
  namespace: monitoring
spec:
  containers:
    - name: uptime-exporter
      image: lukaspastva/uptime-exporter:latest
      env:
        - name: CONFIG_FILE
          value: |
            config:
              prometheus_url: "http://prometheus-operated.monitoring:9090"
              metrics:
                - name: test-metric
                  measureStart: "2023-07-28T18:53:46Z" 
                  queries:
                    - queryType: "kube_deployment_status_replicas"
                      cluster: test-cluster
                      namespace: test-namespace
                      name: test-deployment
                    - queryType: "probe_success"
                      cluster: test-cluster
                      instance: "https://google.com"
              uptimes:
                - start: 123456
                  duration: 1600
                - start: 1234567
                  duration: 1600
