apiVersion: v1
kind: Pod
metadata:
  name: uptime-exporter
  namespace: monitoring
spec:
  containers:
    - name: uptime-exporter
      image: lukaspastva/uptime-exporter:latest
      env:
        - name: CONFIG_FILE
          value: |
            config:
              prometheus_url: "http://prometheus-operated.monitoring:9090"
              metrics:
                - name: test-metric
                  deployments:
                    - cluster: test-cluster
                      namespace: test-namespace
                      name: test-deployment
              uptimes:
                - start: 123456
                  duration: 1600
                - start: 1234567
                  duration: 1600
