name: sys-uptime-exporter
namespace: sys-uptime-exporter
type: DaemonSet

pods:
  - name: sys-uptime-exporter
    repo: lukaspastva/uptime-exporter:latest
    resources: 100
    ports:
      - name: http
        port: 9199
    serviceMonitorEnabled: true
    env:
      - name: CONFIG_FILE
        value: |
          config:
            prometheus_url: "http://prometheus-operated.monitoring:9090"
            metrics:
              - name: test-metric
                measureStart: "2023-08-28T18:53:46Z"
                queries:
                  - queryType: "kube_deployment_status_replicas"
                    cluster: test-cluster
                    namespace: test-namespace
                    name: test-deployment
                  - queryType: "probe_success"
                    cluster: test-cluster
                    instance: "https://google.com"
            uptimes:
              - start: 123456
                duration: 1600
              - start: 1234567
                duration: 1600
