pods:
  sys-uptime-exporter:
    repo: lukaspastva/uptime-exporter:latest
    resources: 100
    ports:
      - name: http
        port: 9199
    serviceMonitor:
      enabled: true
    env:
      - name: CONFIG_FILE
        value: |
          config:
            prometheus_url: "http://prometheus-operated.monitoring:9090"
            metrics:
              - name: test-metric
                measureStart: "2023-08-28T18:53:46Z"
                queries:
                  - queryType: "kube_deployment_status_replicas"
                    cluster: test-cluster
                    namespace: test-namespace
                    name: test-deployment
                  - queryType: "probe_success"
                    cluster: test-cluster
                    instance: "https://google.com"
                  - queryType: "s3_5xx_error_rate"
                    bucket_name: bucket-asdf

            uptimes:
              - start: "2023-11-16T8:00:00Z"
                end: "2023-11-28T8:00:00Z"
